venv_private_diary/private_diary/diary/urls.py
from django.urls import path

from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('dairy-list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary-detail/<int:pk>/', views.CareerDiaryDetail.as_view(), name='diary_detail'),
    path('diary-create/', views.CareerDiaryCreate.as_view(), name='diary_create'),
    path('diary-update/<int:pk>/', views.CareerDiaryUpdate.as_view(), name="diary_update"),
    path('diary-delete/<int:pk>', views.CareerDiaryDelete.as_view(), name="diary_delete"),
]

venv_private_diary/private_diary/private_diary/urls.py
from django.contrib import admin
from django.urls import path, include
#staticファイルの読み込み
from django.contrib.staticfiles.urls import static
#設定ファイルを読み込む
from . import settings_common, settings_dev



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    #all-authのurlsを指定することでDefaultでallauthが搭載しているurls.pyを参照する
    path('accounts/', include('allauth.urls')),
    path('reviews/', include('reviews.urls')),
]

#開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL,
                      document_root = settings_dev.MEDIA_ROOT)

venv_private_diary/private_diary/reviews/urls.py
from django.urls import path

from . import views
app_name = 'reviews'

urlpatterns = [
    path('', views.ReviewsList.as_view(), name='review_list'),
    path('review-detail/<int:pk>', views.ReviewsDetail.as_view(), name="review_detail"),
    path('review-create', views.ReviewsCreate.as_view(), name="review_create"),
    path('review-update/<int:pk>', views.ReviewsUpdate.as_view(), name="review_update"),
    path('review-delete/<int:pk>', views.ReviewsDelete.as_view(), name="review_delete"),
]

venv_private_diary/private_diary/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <link rel="shortcut icon" href="{% static 'img/caricomi.png' %}"/>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

  <!-- My style -->
  <link rel="stylesheet" type = "text/css" href="{% static 'css/mystyle.css' %}">
  {% block head %}{% endblock %}

</head>

<body>

  <!-- Navigation -->
  <div id="wrapper">
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top ">
    <div class="container ">
      <a class="navbar-brand" href="{% url 'diary:index' %}"><img class="rounded-circle mr-3" src="{% static 'img/caricomi.png'%}" alt="">CARICOMI</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block active_inquiry %}{% endblock %}"><a class="nav-link" href="{% url 'diary:inquiry' %}">お問い合わせ</a></li>
          
          {% if user.is_authenticated %}
          <li class="nav-item {% block active_public_diary_list %}{% endblock %}"><a class="nav-link" href="{% url 'reviews:review_list' %}">口コミ</a></li>
            <li class="nav-item {% block active_diary_list %}{% endblock %}"><a class="nav-link" href="{% url 'diary:diary_list' %}">就職日記</a></li>
          {% endif %}
          
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
            </li>

          {% else %}
            <li class="nav-item{% block active_signup %}{% endblock %}">
              <a class="nav-link" href="{% url 'account_signup' %}">登録</a>
            </li>
            <li class="nav-item{% block active_login %}{% endblock %}">
              <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
  {% block header %}{% endblock %}
  {% if messages %}
  <div class="container">
    <div class="row">
      <div class="my-div-style w-100">
        <ul class="messages" style="list-style: none;">
          {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endif %}

  {% block contents %}{% endblock %}


  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; CARICOMI 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vender/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </div>
</body>

</html>