venv_private_diary/private_diary/diary/urls.py
from django.urls import path

from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('dairy-list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary-detail/<int:pk>/', views.CareerDiaryDetail.as_view(), name='diary_detail'),
    path('diary-create/', views.CareerDiaryCreate.as_view(), name='diary_create'),
    path('diary-update/<int:pk>/', views.CareerDiaryUpdate.as_view(), name="diary_update"),
    path('diary-delete/<int:pk>', views.CareerDiaryDelete.as_view(), name="diary_delete"),
]

venv_private_diary/private_diary/private_diary/urls.py
from django.contrib import admin
from django.urls import path, include
#staticファイルの読み込み
from django.contrib.staticfiles.urls import static
#設定ファイルを読み込む
from . import settings_common, settings_dev



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    #all-authのurlsを指定することでDefaultでallauthが搭載しているurls.pyを参照する
    path('accounts/', include('allauth.urls')),
    path('reviews/', include('reviews.urls')),
]

#開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL,
                      document_root = settings_dev.MEDIA_ROOT)

venv_private_diary/private_diary/reviews/urls.py
from django.urls import path

from . import views
app_name = 'reviews'

urlpatterns = [
    path('', views.ReviewsList.as_view(), name='review_list'),
    path('review-detail/<int:pk>', views.ReviewsDetail.as_view(), name="review_detail"),
    path('review-create', views.ReviewsCreate.as_view(), name="review_create"),
    path('review-update/<int:pk>', views.ReviewsUpdate.as_view(), name="review_update"),
    path('review-delete/<int:pk>', views.ReviewsDelete.as_view(), name="review_delete"),
]

venv_private_diary/private_diary/reviews/models.py
from django.db import models
# accountsアプリに作成したCustomUserをインポート
from accounts.models import CustomUser


# Create your models here.

# Service
class Service(models.Model):
    service = models.CharField(verbose_name="サービス名", max_length=25, default=1)
    url = models.URLField(verbose_name="URL")
    img = models.ImageField(verbose_name="画像")

    class Meta:
        verbose_name_plural = 'Service'

    def __str__(self):
        return self.service

# 口コミモデル


class Review(models.Model):
    user = models.ForeignKey(
        CustomUser, verbose_name="ユーザー", on_delete=models.PROTECT)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    SERVICE_QUALITY_CHOICES = [
        # (データベースに登録されている値, 表示上の値) ※表示上の値はget_フィールド名_displayで取得
        ('5', '★★★★★'),
        ('4', '★★★★'),
        ('3', '★★★'),
        ('2', '★★'),
        ('1', '★')
    ]
    quality = models.CharField(
        verbose_name="サポートの質", choices=SERVICE_QUALITY_CHOICES, max_length=5)
    content = models.TextField(verbose_name="サービスの感想")
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="更新日時", auto_now=True)

    class Meta:
        verbose_name_plural = 'Review'

    def __str__(self):
        return self.service

venv_private_diary/private_diary/reviews/forms.py
from django import forms

#models.pyからDiaryモデルクラスをインポート
from .models import Review



#Review作成フォーム
class ReviewCreateForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            'service',
            'quality',
            'content',
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class SearchForm(forms.Form):
    service_name = forms.CharField(initial="",
                                    required=False, 
                                    label="サービス名",
                                    widget=forms.TextInput(attrs={"placeholder":"サービス名を検索"})
    )

venv_private_diary/private_diary/reviews/views.py
#viewsのgeneric（汎用ビューが沢山あるモジュール）
from django.views import generic
#forms.pyから使用するフォームクラスをインポート
from .forms import ReviewCreateForm, SearchForm
#URLの逆引きを行えて、URLのハードコーディングを防げる
from django.urls import reverse_lazy
#送信が成功した際にメッセージを表示するメソッド
from django.contrib import messages
#loggingをインポート
import logging
#ログインしていないとアクセスできない状態にするもの
from django.contrib.auth.mixins import LoginRequiredMixin
#models.pyのReviewsモデルをインポート
from .models import CustomUser, Review, Service

from django.db.models import Q

from . import views

###################################################################
#loggerを取得
logger = logging.getLogger(__name__)



#日記一覧表示機能
class ReviewsList(LoginRequiredMixin, generic.ListView):
    model = Review
    template_name = 'reviews/review_list.html'
    paginate_by = 5
    
    #post通信時に行う処理
    def post(self, request, *args, **kwargs):
        #ページが変わってもフォームに値が残るようにする
        form_value = self.request.POST.get('service_name', None)
        request.session['form_value'] = form_value
        
        #検索時にページネーションに関連したエラーを防ぐ　※後で使わないとどうなるか試す
        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()
        
        return self.get(request, *args, **kwargs)
    
    #ListViewが返すtemplateなどの表示するobject
    def get_context_data(self, **kwargs):
        #オーバーライドする
        context = super().get_context_data(**kwargs)
        
        #sessionに値がある場合、その値をセットする(ページングしても値が変わらないように)
        service_name = ''
        #ある場合
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            service_name = form_value
        default_data = {'service_name':service_name}
        
        search_form =SearchForm(initial=default_data)#検索フォーム
        #テンプレートで使えるようにする
        context['search_form'] = search_form
        
        return context
    
    
    
    #投稿された日記を作られた順に並べて表示するメソッド
    def get_queryset(self):
        #sessionに値がある場合、その値でクエリを発行する
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            service_name = form_value
            
            #検索条件
            condition_service_name = Q()
            
            if len(service_name != 0 and service_name):
                condition_service_name = Q(service_name__icontains=service)
                
            return Review.objects.select_related().filter(condition_service_name)

        else:
            return Review.objects.none()



#レビューの詳細表示
class ReviewsDetail(LoginRequiredMixin, generic.DetailView):
    model = Review
    template_name = 'reviews/review_detail.html'
    
    
#レビュー作成機能
class ReviewsCreate(LoginRequiredMixin, generic.CreateView):
    model = Review
    template_name = 'reviews/review_create.html'
    form_class = ReviewCreateForm
    #正常に処理が終わった時の遷移先
    success_url = reverse_lazy('reviews:review_list')

    #フォームのバリデーションに以上がなかった時の処理
    def form_valid(self, form):
        #commit=falseを指定するとデータにまだ保存されていない状態のオブジェクトが返される
        diary = form.save(commit=False)
        #diaryのuserIdに自動生成されるuseIDを代入
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)
    
    #フォームのバリデーションにエラーがなかった場合の処理
    def form_invalid(self, form):
        messages.error(self.request, '日記の作成に失敗しました。')
        return super().form_invalid(form)


#レビュー編集機能
class ReviewsUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Review
    template_name = 'reviews/review_update.html'
    #フォームフィールドはCreateフォームと変わらないため使いまわす
    form_class = ReviewCreateForm
    
    
    def get_success_url(self):
        """逆引きメソッド"""
        return reverse_lazy('reviews:review_detail', kwargs={'pk':self.kwargs['pk']})
    
    def form_valid(self, form):
        """正常にフォームが入力された時に実行されるメソッド"""
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        """正常にフォームが入力されなかった時に実行されるメソッド"""
        messages.success(self.request, '日記を更新できませんでした。')
        return super().form_invalid(form)

#レビュー削除機能
class ReviewsDelete(LoginRequiredMixin, generic.DeleteView):
    model = Review
    template_name = 'reviews/review_delete.html'
    #削除を正常に行えたら日記一覧ページへと遷移する
    success_url = reverse_lazy('reviews:review_list')
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '日記を削除しました。')
        return super().delete(request, *args, **kwargs)

venv_private_diary/private_diary/templates/reviews/review_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}口コミ作成 | CARICOMI{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary mb-5" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/reviews/review_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}口コミ削除 | CARICOMI{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'reviews:review_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}口コミ詳細 | CARICOMI{% endblock %}

{% block active_review_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}


{% block contents %}
<div class="container mt-3">
    <div class="my-div-style w-100">
        <!--サービス名-->
        <div class="row">
            <div class="col-3">
                <strong>サービス名</strong>
            </div>
            <div class="col-9">
                {{ object.service_name }}
            </div>
        </div>
        <hr>
        <!--サポートの質-->
        <div class="row">
            <div class="col-3">
                <strong>サポートの質</strong>
            </div>
            <div class="col-9">
                {{ object.get_support_quality_display }}
            </div>
        </div>
        <hr>
        <!--サービスの感想-->
        <div class="row">
            <div class="col-3">
                <strong>サービスの感想</strong>
            </div>
            <div class="col-9">
                {{ object.subject }}
            </div>
        </div>
        <hr>
        <!--投稿者-->
        <div class="row">
            <div class="col-3">
                <strong>投稿者</strong>
            </div>
            <div class="col-9">
                {{ object.user }}
            </div>
        </div>
        <hr>
        <!--作成日時-->
        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>
        <hr>
        <!--更新日時-->
        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.update_at }}
            </div>
        </div>
        {% if object.user == user %}
            <a class="btn btn-success mt-5 mb-3" href="{% url 'reviews:review_update' object.pk %}">編集</a>
            <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'reviews:review_delete' object.pk %}">削除</a>
        {% endif %}
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/reviews/review_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}口コミ一覧 | CARICOMI{% endblock %}

{% block active_review_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-10 mx-auto">
                <div class="clearfix">
                    <a href="{% url 'reviews:review_create' %}" class="btn btn-primary float-right">新規作成</a>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in search_form %}
                        <div class="form-group form_inline">
                            <div class="col-md-8">
                                {{ field }}
                        {% endfor %}
                            <input type="submit"  id="button" name="button" value="🔍">
                            </div>
                        </div>
                    </form>
                </div>
                {% for reviews in reviews_list %}
                    <div class="post-preview">
                        <a href="{% url 'reviews:review_detail' reviews.pk %}">
                            <h2 class="post-title">{{ reviews.service_name }}</h2>
                            <h3 class="post-subtitle">{{ reviews.get_support_quality_display }}</h3>
                        </a>
                        <p class="post-meta">{{ reviews.created_at }}</p>
                    </div>
                    <hr>
                {% empty %}
                    <p>日記がありません。</p>
                {% endfor %}

                <!--ページネーション処理-->
                {% if is_paginated %}
                <ul class="pagination">
                    <!--前ページへのリンク-->
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}">
                            <span aria-hidden='true'>&laquo;</span>
                        </a></li>
                    {% endif %}

                    <!--ページ数表示-->
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <!--次ページへのリンク-->
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/reviews/review_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}口コミ編集 | CARICOMI{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'reviews:review_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}