venv_private_diary/private_diary/diary/urls.py
from django.urls import path

from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('dairy-list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary-detail/<int:pk>/', views.CareerDiaryDetail.as_view(), name='diary_detail'),
    path('diary-create/', views.CareerDiaryCreate.as_view(), name='diary_create'),
    path('diary-update/<int:pk>/', views.CareerDiaryUpdate.as_view(), name="diary_update"),
    path('diary-delete/<int:pk>', views.CareerDiaryDelete.as_view(), name="diary_delete"),
]

venv_private_diary/private_diary/private_diary/urls.py
from django.contrib import admin
from django.urls import path, include
#staticファイルの読み込み
from django.contrib.staticfiles.urls import static
#設定ファイルを読み込む
from . import settings_common, settings_dev



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    #all-authのurlsを指定することでDefaultでallauthが搭載しているurls.pyを参照する
    path('accounts/', include('allauth.urls')),
    path('reviews/', include('reviews.urls')),
]

#開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL,
                      document_root = settings_dev.MEDIA_ROOT)

venv_private_diary/private_diary/diary/models.py
from django.db import models
#accountsアプリに作成したCustomUserモデルをインポート
from accounts.models import CustomUser

#就職日記モデル
class CareerDiary(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name="ユーザー", on_delete=models.PROTECT)
    company_name = models.CharField(verbose_name="企業名", max_length=25)
    interview_date = models.DateField(verbose_name="面接日")
    
    SELECTION_STAGE_CHOICES = [
        ('CASUAL', 'カジュアル面談'),
        ('1次面接', '1次面接'),
        ('2次面接', '2次面接'),
        ('3次面接', '3次面接'),
        ('4次面接', '4次面接'),
        ('5次面接', '5次面接'),
        ('最終選考', '最終選考')
    ]
    selection_stage = models.CharField(verbose_name="選考段階", choices=SELECTION_STAGE_CHOICES, max_length=7, blank=False, default=0)
    content = models.TextField(verbose_name="面接記録")
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    update_at = models.DateTimeField(verbose_name="更新日時", auto_now=True)
    
    class Meta:
        verbose_name_plural = 'CareerDiary'
        
    def __str__(self):
        return self.company_name

venv_private_diary/private_diary/diary/forms.py
from django import forms

from django.core.mail import EmailMessage
#models.pyからDiaryモデルクラスをインポート
from .models import CareerDiary

#問い合わせ用フォーム
class InquiryForm(forms.Form):
    name = forms.CharField(label = 'お名前', max_length=30)
    email = forms.EmailField(label = 'メールアドレス')
    title = forms.CharField(label = 'タイトル', max_length= 30)
    message = forms.CharField(label = 'メッセージ', widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        '''
        fields["フィールド名"].widget.attrs['class'] = 'クラス名'
        fields["フィールド名"].widget.attrs['placeholder'] = 'プレースホルダー名'
        attrsメソッドでHTML属性のプロパティを取得
        '''
        
        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'
        
        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'
        
        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください'
        
        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'タイトルを入力してください'
    
    #メールを送るメソッド
    def send_email(self):
        #フォームバリデーションを通ったデータを取得して代入
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']
        
        #件名（subject）を設定
        subject = f'お問い合わせ{title}'
        #本文を設定
        message = f'送信者名：{name}\nメールアドレス：{email}\nメッセージ：{message}'
        #送信者を設定
        from_email = 'admin@example.com'
        #受信者のリスト
        to_list = [
            'test@example.com'
        ]
        #ccのリスト
        cc_list = [
            email
        ]
        
        #EmailMessageインスタンスを作成
        message = EmailMessage(
            subject = subject,
            body = message,
            from_email = from_email,
            to = to_list,
            cc = cc_list,
        )
        
        #send()メソッドを使用してメッセージを作成する
        message.send()


#CareerDiary作成フォーム
class CareerDiaryCreateForm(forms.ModelForm):
    class Meta:
        model = CareerDiary
        fields = [
            'company_name',
            'interview_date',
            'selection_stage',
            'content',
        ]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

venv_private_diary/private_diary/diary/views.py
#viewsのgeneric（汎用ビューが沢山あるモジュール）
from django.views import generic
#forms.pyから使用するフォームクラスをインポート
from .forms import InquiryForm, CareerDiaryCreateForm
#URLの逆引きを行えて、URLのハードコーディングを防げる
from django.urls import reverse_lazy
#送信が成功した際にメッセージを表示するメソッド
from django.contrib import messages
#loggingをインポート
import logging
#ログインしていないとアクセスできない状態にするもの
from django.contrib.auth.mixins import LoginRequiredMixin
#models.pyのCareerDiaryモデルをインポート
from .models import CustomUser, CareerDiary


from . import views

#########################################################


#loggerを取得
logger = logging.getLogger(__name__)

# Create your views here.
class IndexView(generic.TemplateView):
    template_name = 'diary/index.html'
    
class InquiryView(generic.FormView):
    #テンプレートとして使用するhtmlファイルを指定
    template_name = 'diary/inquiry.html'
    #使用するフォームクラスを指定
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')
    
    def form_valid(self, form):
        #forms.pyでInquiryFormに定義したsend_email()メソッドを呼び出す
        form.send_email()
        #送信成功時のメッセージ表示
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info(f"Inquiry sent by{form.cleaned_data['name']}")
        return super().form_valid(form)
    
    

#日記一覧表示機能
class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = CareerDiary
    template_name = 'diary/diary_list.html'
    paginate_by = 2
    
    #投稿された日記を作られた順に並べて表示するメソッド
    def get_queryset(self):
        diaries = CareerDiary.objects.filter(user=self.request.user).order_by('-created_at')
        #ページネイションを指定 クラスベースView使ったらヤバいほど簡単
        return diaries



#日記の詳細表示
class CareerDiaryDetail(LoginRequiredMixin, generic.DetailView):
    model = CareerDiary
    template_name = 'diary/diary_detail.html'
    
    
#CareerDiary作成機能
class CareerDiaryCreate(LoginRequiredMixin, generic.CreateView):
    model = CareerDiary
    template_name = 'diary/diary_create.html'
    form_class = CareerDiaryCreateForm
    #正常に処理が終わった時の遷移先
    success_url = reverse_lazy('diary:diary_list')

    #フォームのバリデーションに以上がなかった時の処理
    def form_valid(self, form):
        #commit=falseを指定するとデータにまだ保存されていない状態のオブジェクトが返される
        diary = form.save(commit=False)
        #diaryのuserIdに自動生成されるuseIDを代入
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)
    
    #フォームのバリデーションにエラーがなかった場合の処理
    def form_invalid(self, form):
        messages.error(self.request, '日記の作成に失敗しました。')
        return super().form_invalid(form)


#日記編集機能
class CareerDiaryUpdate(LoginRequiredMixin, generic.UpdateView):
    model = CareerDiary
    template_name = 'diary/diary_update.html'
    #フォームフィールドはCreateフォームと変わらないため使いまわす
    form_class = CareerDiaryCreateForm
    
    
    def get_success_url(self):
        """逆引きメソッド"""
        return reverse_lazy('diary:diary_detail', kwargs={'pk':self.kwargs['pk']})
    
    def form_valid(self, form):
        """正常にフォームが入力された時に実行されるメソッド"""
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        """正常にフォームが入力されなかった時に実行されるメソッド"""
        messages.success(self.request, '日記を更新できませんでした。')
        return super().form_invalid(form)

#日記削除機能
class CareerDiaryDelete(LoginRequiredMixin, generic.DeleteView):
    model = CareerDiary
    template_name = 'diary/diary_delete.html'
    #削除を正常に行えたら日記一覧ページへと遷移する
    success_url = reverse_lazy('diary:diary_list')
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '日記を削除しました。')
        return super().delete(request, *args, **kwargs)

venv_private_diary/private_diary/templates/diary/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記作成 | PrivateDiary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary mb-5" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/diary/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記削除 | PrivateDiary{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/diary/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記詳細 | PrivateDiary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="my-div-style w-100">
        <!--タイトルを表示-->
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{ object.company_name }}
            </div>
        </div>
        <hr>
        <!--面談日時-->
        <div class="row">
            <div class="col-3">
                <strong>面談日時</strong>
            </div>
            <div class="col-9">
                {{ object.interview_date }}
            </div>
        </div>
        <hr>
        <!--選考段階-->
        <div class="row">
            <div class="col-3">
                <strong>選考段階</strong>
            </div>
            <div class="col-9">
                {{ object.selection_stage }}
            </div>
        </div>
        <hr>
        <!--本文-->
        <div class="row">
            <div class="col-3">
                <strong>感想</strong>
            </div>
            <div class="col-9">
                {{ object.content }}
            </div>
        </div>
        <hr>

        <!--作成日時を表示-->
        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>
        <hr>

        <!--更新日時-->
        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>
        {% if object.user == user %}
            <a class="btn btn-success mt-5 mb-3" href="{% url 'diary:diary_update' object.pk %}">編集</a>
            <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'diary:diary_delete' object.pk %}">削除</a>
        {% endif %}
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/diary/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記一覧 | PrivateDiary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-10 mx-auto">
                <div class="clearfix">
                    <a href="{% url 'diary:diary_create' %}" class="btn btn-primary float-right">新規作成</a>
                </div>
                {% for CareerDiary in careerdiary_list %}
                    <div class="post-preview">
                        <a href="{% url 'diary:diary_detail' CareerDiary.pk %}">
                            <h2 class="post-title">{{ CareerDiary.company_name }}</h2>
                            <h3 class="post-subtitle">{{ CareerDiary.selection_stage }}</h3>
                        </a>
                        <p class="post-meta">{{ CareerDiary.created_at }}</p>
                    </div>
                    <hr>
                {% empty %}
                    <p>日記がありません。</p>
                {% endfor %}

                <!--ページネーション処理-->
                {% if is_paginated %}
                <ul class="pagination">
                    <!--前ページへのリンク-->
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}">
                            <span aria-hidden='true'>&laquo;</span>
                        </a></li>
                    {% endif %}

                    <!--ページ数表示-->
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <!--次ページへのリンク-->
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/diary/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集 | PrivateDiary{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

venv_private_diary/private_diary/templates/diary/index.html
<!-- base.htmlに出力する -->
{% extends 'base.html' %}
<!-- staticファイルを読み込む -->
{% load static %}
<!-- titleを設定しbase.htmlに出力した際に反映させる -->
{% block title %}
就職サービス口コミサイト | Caricomi
{% endblock %}




<!-- base.htmlのheader部分に出力する -->
{% block header %}
<header class= "masthead text-center text-white">
    <div class= "masthead-content">
        <div class= "container">
            <h1 class="masthead-heading mb-0">CARICOMI</h1>
            <h2 class="masthead-subheading mb-o">キャリコミ</h2>
            <h2 class=" mb-o">〜 就職サービス口コミサイト 〜</h3>
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">ログイン</a>
        </div>
    </div>

    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/career01.png' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">自分の就職活動を管理できる</h2>
                    <p class="lead">日記のように面談記録や企業情報を管理できます！！</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/career02.png' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">他の人の口コミも見れる</h2>
                    <p class="lead">口コミ機能でみんなが利用したサービスの情報も見れます！！</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/career03.png' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">就職活動を効率的に！</h2>
                    <p class="lead">様々な機能を使い就職活動を効率的に進められます！！</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

venv_private_diary/private_diary/templates/diary/inquiry.html
{% extends 'base.html' %}
{% load static %}

{% block title %}お問い合わせ | Private {% endblock %}

{% block active_inquiry %}active{% endblock %}


{% block head %}<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">{% endblock %}

{% block contents %}
<div class="container mt-3">
    <div class="row justify-content-center ">
        <div class="my-div-style ">
            <form class=""  method= 'post'>
                <!--CSRF対策用タグ　※post通信でこのタグをつけていないとDjangoは403エラーを返す-->
                {% csrf_token %}
                {{form.non_field_errors}}
                <table class="table  table-active text-center">
                    <tbody class="">
                        {% for field in form %}
                            <tr class="mb-3 ">
                                <th class="t">{{field.label}}</th>
                                <td>{{field}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="offset-sm-4 col-sm-7 mt-4 mb-4">
                    <button class="btn btn-info" type="submit">送信</button>
                </div>
            </form>
            
        </div>
    </div>
</div>
{% endblock %}